coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:
        paths:
          - "tests/"
        target: 100%
      source:
        paths:
          - "jupytext/"
        target: 0%
        #threshold: 0.002
    patch:
      default:
        target: 0%  # new contributions should have a coverage at least equal to target
